### ISSUE TITLE
What are the list of things that will be required to take this to 1.0? 

### ISSUE THREAD

**Issue by ArEnSc** [fastai/swiftai#18]

**Comment by saeta** [comment]
I don't want to speak for Jeremy, Sylvain, or the rest of the fast.ai community, but I suspect SwiftAI might not want to go 1.0 until the underlying Swift for TensorFlow platform achieves 1.0. On that front, we have a number of key aspects we need to improve (chiefly around performance, but also distributed training / inference, and ensuring the underlying abstractions support high quality high-level APIs such as SwiftAI itself!). These are all top-of-mind for the team, but we're optimizing for high quality, instead of shortest-time-to-1.0. :-)

**Comment by sgugger** [comment]
I agree with @saeta . In general, all discussion around the library should be on the [forum](https://forums.fast.ai/c/swiftai) so that all the community can see :) 
Closing this as we keep issues for known bugs only.
